FROM nginx:alpine

# Path harus relatif terhadap lokasi build context (root)
COPY nginx/conf.d/app.conf /etc/nginx/conf.d/default.conf

# Tambahkan ini agar Nginx punya file statis (CSS/JS/Index) yang sama dengan Laravel
WORKDIR /var/www
COPY public /var/www/public
