FROM nginx:alpine
# 1. Copy config
COPY nginx/conf.d/app.conf /etc/nginx/conf.d/default.conf
# 2. Set folder kerja
WORKDIR /var/www
# 3. Copy folder public (Wajib ada agar Nginx tidak error realpath)
COPY public /var/www/public
