FROM nginx:alpine

# Copy config Anda ke lokasi default agar aktif
COPY nginx/conf.d/app.conf /etc/nginx/conf.d/default.conf

# WAJIB: Folder public harus ada di sini agar sesuai dengan 'root /var/www/public'
WORKDIR /var/www
COPY public /var/www/public
