version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /var/www

    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

    stop_grace_period: 30s

    deploy:
      update_config:
        parallelism: 1
        order: stop-first

      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s

    networks:
      - laravel-network

  nginx:
    image: nginx:alpine

    ports:
      - "8000:80"

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

    depends_on:
      - app

    stop_grace_period: 30s

    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s

    networks:
      - laravel-network

  db:
    image: mysql:8.0

    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}

    volumes:
      - laravel-data:/var/lib/mysql

    deploy:
      restart_policy:
        condition: any

    networks:
      - laravel-network

networks:
  laravel-network:

volumes:
  laravel-data:
